# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-03-13 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoodManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('title', models.CharField(max_length=128, verbose_name='心情标题')),
                ('cont', models.CharField(max_length=512, verbose_name='心情内容')),
            ],
            options={
                'verbose_name': '心情管理',
                'verbose_name_plural': '心情管理',
                'db_table': 'mood_manage',
            },
        ),
    ]
