# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-03-13 10:01
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('auther', models.CharField(max_length=20, verbose_name='作者')),
                ('summary', models.CharField(max_length=256, verbose_name='文章简介')),
                ('read_times', models.IntegerField(default=0, verbose_name='阅读量')),
                ('sum_up', models.IntegerField(default=0, verbose_name='点赞数')),
                ('column', models.SmallIntegerField(choices=[(0, '建站'), (1, '框架'), (2, '前端'), (3, '数据库'), (4, '趣谈'), (5, '生活')], default=0, verbose_name='栏目')),
                ('content', ckeditor.fields.RichTextField(verbose_name='文章主体内容')),
            ],
            options={
                'verbose_name': '文章管理',
                'verbose_name_plural': '文章管理',
                'db_table': 'article_manage',
            },
        ),
    ]
