# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-03-13 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('sum_up', models.IntegerField(default=0, verbose_name='点赞数')),
                ('comment', models.TextField(max_length=500)),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comment.CommentManage')),
            ],
            options={
                'verbose_name': '博客评论类',
                'verbose_name_plural': '博客评论类',
                'db_table': 'comment_manage',
            },
        ),
    ]
